### ISSUE TITLE
Support Alpine Linux (musl)

### ISSUE THREAD

**Issue by nikolay** [gulien/orbit#14]
Orbit can be used within Docker containers.

**Comment by gulien** [comment]
Hi @nikolay!

Thank you for your interest! Which GOOS and GOARCH should be use to build a binary for Alpine?

**Comment by nikolay** [comment]
@gulien I am not an expert but it seems that you need these: `GOOS=linux GOARCH=amd64 CGO_ENABLED=0`.

**Comment by gulien** [comment]
Actually there is already a binary using these parameters. See here: https://github.com/gulien/orbit/blob/master/goreleaser.yml.

Tell me if it works 😄

**Comment by gulien** [comment]
Feel free to reopen this issue if it's still relevant!

**Comment by nikolay** [comment]
@gulien Sorry, I was on some sort of vacation, but I will validate later this week or next when I'm back!

**Comment by gulien** [comment]
Ok no problem :)
