### ISSUE TITLE
Question : how to check if file exists ?

### ISSUE THREAD

**Issue by kpym** [gulien/orbit#39]
Is it possible to check if some file exists in `orbit.yml`.
I want to create a conditional task that runs one command if some file exists and another one if not.

Thanks in advance for your help.

**Comment by gulien** [comment]
Hello @kpym,

AFAIK, there is currently no template method for that. You have to rely on a OS native command 🤔

**Comment by kpym** [comment]
@gulien Can I recover the result of shell command in template variable in a way to use after that something like `{{ if eq $result 0 }}` ?

**Comment by gulien** [comment]
No you can’t, for such requirements you have to rely on a custom script ^^

**Comment by kpym** [comment]
😢 Bad news. Deciding what to do depending on the file existence is very useful feature.
In any case, thanks for your answer and for your work. 🙏

**Comment by gulien** [comment]
Yep, there are a lot of features that could be nice to add 👍 I’ll try to find some time in the future !
